version: 2.1
orbs:
  python: circleci/python@2.1.1
  heroku: circleci/heroku@1.2.6
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  build_and_test:
    executor: python/default
    docker:
      - image: cimg/python:3.12.3-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: |
          pip install --upgrade pip
          python --version
          chmod 0755 requirements.txt
          pip install -r requirements.txt
          mkdir reports
          pytest

      - store_artifacts:
          path: reports

workflows:
  test_my_app:
    jobs:
      - build_and_test